_target_: src.core.models.species_detector.SpeciesDetector
in_features: 128
lamdba: 0.1
beta: 0.0
label_smoothing: 0.0
regularisation_mode: L1
attn_dim: 10
train_sample_size: 1
eval_sample_size: 100
clf_learning_rate:
attn_learning_rate:
attn_weight_decay:
