_target_: src.core.models.vae_soundscape_generator.VAESoundscapeGenerator
num_features: 128
num_points: 10
num_samples: 10
num_rnn_layers: 2
learning_rate: 4.e-5
optimiser_cls: torch.optim.AdamW
scheduler_cls: torch.optim.lr_scheduler.CosineAnnealingLR
scheduler_config:
  T_max: 40_000
  eta_min: 4.e-7

