defaults:
  - /model: sivae3

_target_: src.core.algorithms.vae.SoundscapeVAE
learning_rate: 4.e-5
optimiser_cls: torch.optim.AdamW
scheduler_cls: torch.optim.lr_scheduler.CosineAnnealingLR
scheduler_config:
  T_max: 180_000
  eta_min: 1.e-5
