_target_: lightning.pytorch.profilers.PyTorchProfiler
record_shapes: True
profile_memory: True
with_stack: True
on_trace_ready:
  _target_: torch.profiler.tensorboard_trace_handler
  dir_name: ${paths.root_dir}/logs/
