# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}
# path to data directory
data_dir: /mnt/data0/${oc.env.USER}/data
# path to data directory
results_dir: /mnt/data0/${oc.env:USER}/experiments
# path to model checkpoints
checkpoint_dir: /mnt/data0/${oc.env:USER}/checkpoints
# path to saved models
model_dir: /mnt/data0/${oc.env:USER}/models
# path to logging directory
log_dir: /src/thetis2/${oc.env.USER}/logs/
# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}
# path to working directory
work_dir: ${hydra:runtime.cwd}
