#!/bin/bash

# Cross Val Results
#         model      scope  clf_learning_rate  l1_penalty  attn_learning_rate  attn_weight_decay  epoch     auROC        AP     score
# 138   birdnet  RFCX_bird               0.01        0.05              0.0010              0.001    599  0.962361  0.550907  1.513268
# 586   birdnet  RFCX_frog               0.01        0.01              0.0010              0.010    949  0.926537  0.394483  1.321020
# 1112  birdnet      SO_EC               0.01        0.05              0.0005              0.001    999  0.917581  0.518909  1.436491
# 1602  birdnet      SO_UK               0.01        0.05              0.0005              0.001    299  0.885744  0.563532  1.449276

RESULTS_DIR=./results/birdnet_species_detectors/

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=300 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=SO_UK \
   data.version=v0 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=5.e-4 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=so_uk_birdnet.pt:v0 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=300 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=SO_UK \
   data.version=v1 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=5.e-4 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=so_uk_birdnet.pt:v1 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=300 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=SO_UK \
   data.version=v2 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=5.e-4 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=so_uk_birdnet.pt:v2 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=1000 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=SO_EC \
   data.version=v0 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=5.e-4 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=so_ec_birdnet.pt:v0 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=1000 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=SO_EC \
   data.version=v1 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=5.e-4 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=so_ec_birdnet.pt:v1 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=1000 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=SO_EC \
   data.version=v2 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=5.e-4 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=so_ec_birdnet.pt:v2 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=600 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=RFCX_bird \
   data.version=v0 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=1.e-3 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=rfcx_bird_birdnet.pt:v0 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=600 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=RFCX_bird \
   data.version=v1 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=1.e-3 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=rfcx_bird_birdnet.pt:v1 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=600 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=RFCX_bird \
   data.version=v2 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=5.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=1.e-3 \
   model.attn_weight_decay=1.e-3 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=rfcx_bird_birdnet.pt:v2 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=950 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=RFCX_frog \
   data.version=v0 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=1.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=1.e-3 \
   model.attn_weight_decay=1.e-2 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=rfcx_frog_birdnet.pt:v0 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=950 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=RFCX_frog \
   data.version=v1 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=1.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=1.e-3 \
   model.attn_weight_decay=1.e-2 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=rfcx_frog_birdnet.pt:v1 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR

WANDB_MODE=offline uv run src/cli/train.py \
   +experiment=species_detector \
   trainer.max_epochs=950 \
   +trainer.limit_val_batches=0.0 \
   data.root=./data/soundscape_birdnet_embeddings \
   data.model=birdnet \
   data.scope=RFCX_frog \
   data.version=v2 \
   data.val_prop=0.0 \
   model.in_features=1024 \
   model.train_sample_size=null \
   model.eval_sample_size=null \
   model.pool_method=prob_attn \
   model.clf_learning_rate=1.e-2 \
   model.l1_penalty=1.e-2 \
   model.attn_dim=10 \
   model.attn_learning_rate=1.e-3 \
   model.attn_weight_decay=1.e-2 \
   model.key_per_target=true \
   callbacks.model_checkpoint.dirpath=$RESULTS_DIR/checkpoints \
   callbacks.model_checkpoint.filename=rfcx_frog_birdnet.pt:v2 \
   callbacks.model_checkpoint.monitor=null \
   callbacks.model_checkpoint.save_last=null \
   paths.results_dir=$RESULTS_DIR
