#!/bin/bash

WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=majestic-lesson data=sounding_out_chorus evaluator=lightning_test "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/majestic-lesson/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/majestic-lesson/
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=varied-serpent data=sounding_out_chorus evaluator=lightning_test "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/varied-serpent/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/varied-serpent/
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=small-enrico data=sounding_out_chorus evaluator=lightning_test "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/small-enrico/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/small-enrico/
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=welcome-college data=sounding_out_chorus evaluator=lightning_test "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/welcome-college/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/welcome-college/
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=vivid-asia data=sounding_out_chorus evaluator=lightning_test "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/vivid-asia/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/vivid-asia/

# embed features
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=majestic-lesson data=sounding_out_chorus evaluator=lightning_predict "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/majestic-lesson/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/majestic-lesson/ callbacks.vae_embeddings.frame_hop_length=192
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=varied-serpent data=sounding_out_chorus evaluator=lightning_predict "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/varied-serpent/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/varied-serpent/ callbacks.vae_embeddings.frame_hop_length=192
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=small-enrico data=sounding_out_chorus evaluator=lightning_predict "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/small-enrico/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/small-enrico/ callbacks.vae_embeddings.frame_hop_length=192
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=welcome-college data=sounding_out_chorus evaluator=lightning_predict "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/welcome-college/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/welcome-college/ callbacks.vae_embeddings.frame_hop_length=192
WANDB_MODE=offline uv run main.py eval +experiment=sivae seed=24 run_id=vivid-asia data=sounding_out_chorus evaluator=lightning_predict "ckpt_path=/its/home/kag25/models/v3/sivae_translation_idx/vivid-asia/step\=180000.ckpt" paths.results_dir=/its/home/kag25/experiments/v3/translation_idx/vivid-asia/ callbacks.vae_embeddings.frame_hop_length=192
